### PR TITLE
Changed "blueprint" to "template".

### PR DESCRIPTION
**Pull request by phips**
### Issue & Steps to Reproduce / Feature Request

Folks — we don't use 'blueprint' nomenclature any longer, it's a 'template'. This change makes using the cli feel out of date and out of step with the UI.

### Solution

I changed everything to use 'template' in the CLI, leaving the API comms to be 'blueprintId' of course. Tests updated and ran 🆗 Also did a live run and it was also ✅ 

Bumped version to 1.0.23…
```
e288901c39f4# env0 version
1.0.23
```

However, I don't know if this is welcome or 100% correct. I am technically inept 😆 and would say _caveat emptor_. If it looks useful, please check all my working 😄 

Screenshot 2022-10-07 at 14 27 02

Screenshot 2022-10-07 at 14 26 52

Screenshot 2022-10-07 at 14 29 27

### CODE REVIEW

**Review by avnerenv0 — COMMENTED** [review]
Sorry @phips ...

Since we are changing the TEMPLATE_ID environment variable as input, this would be a breaking change. It's also strange that the CLI would still have template id accepted as `-b`.

We should do a little more work here and make sure we stay backwards compatible, but if someone inputs `BLUEPRINT_ID` or `-b` we should log a warning that those options are deprecated and will be removed in a future major version. 

Do you think that's possible?
Or do you think this should be a priority and we'll put someone from the dev team on it?

**Comment by phips** [comment]
No apology necessary @avnerenv0! Thanks for reviewing. It was a first attempt at trying to bring the CLI up to date with the UI, and could really use a proper developer on it (and not rusty old me). I kept `-b` in this edit because I figured it would maintain some semblance of backwards compatibility — plus, the more logical `-t` is in use. So, it was a pragmatic suggestion. Your suggestion of 'doing it properly' with a change but deprecation warning is *far better* than my half-arsed approach 😆

If somebody on the dev team has time to fix this properly, I think it would be worthwhile, yes. Having it aligned with the UI is _a good thing_ and will certainly help us tell a more up to date story (i.e. a blog post) about how to integrate CLI use.

**Comment by avnerenv0** [comment]
[Change the CLI to use "template" instead of "blueprint"](https://trello.com/c/5arnDW3n/7758-change-the-cli-to-use-template-instead-of-blueprint)

**Comment by avnerenv0** [comment]
Sorry again @phips but after an R&D discussion we've decided this is not a priority, it's not really a pain to anyone and the usage of the CLI is very very low.

**Pull request closed without merging**
